# Generated by Django 4.2.20 on 2025-03-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
