# Generated by Django 4.2.7 on 2025-05-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_forumreply_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.CharField(default='https://img.freepik.com/free-vector/blue-circle-with-white-user_78370-4707.jpg?t=st=1746949129~exp=1746952729~hmac=2e139c08af0e5fb473952938f8e689336a8a643d2df0fd1310d8d571ba8872ee&w=740', max_length=200),
        ),
    ]
