# Generated by Django 4.2.7 on 2025-05-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_instructorprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
