# Generated by Django 4.2.7 on 2025-08-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_quizattempt_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link for live meeting/video conference', null=True),
        ),
    ]
